[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1sjr0InSVTUiccDi_0mnm5gWDbQGTfxfo?usp=sharing)

# Tensors

Tensors are n-dimensional arrays of numbers and serve as the foundational elements in machine learning. Their role is to represent data numerically..

https://github.com/MinyoungHer/Pytorch-study

<img src="https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-scalar-vector-matrix-tensor.png" alt="image" style="max-width:100px; max-height:100px;">

In [ ]:
import torch

In [ ]:
# scalar
scalar = torch.tensor(17)
print(scalar)
print(scalar.ndim)
print(scalar.item())

tensor(17)
0
17


In [ ]:
# vector
vector = torch.tensor([17, 14])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([17, 14])
1
torch.Size([2])


In [ ]:
# matrix
matrix = torch.tensor([[17, 14],
                       [1, 2]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)

tensor([[17, 14],
        [ 1,  2]])
2
torch.Size([2, 2])


In [ ]:
# tensors
tensor = torch.tensor([[[1, 2, 3, 8],
                        [3, 6, 9, 7],
                        [2, 4, 5, 6]]])
print(tensor)
print(tensor.ndim)
print(tensor.shape)

tensor([[[1, 2, 3, 8],
         [3, 6, 9, 7],
         [2, 4, 5, 6]]])
3
torch.Size([1, 3, 4])


## Tensor creation

In [ ]:
# random tensors
random_tensor = torch.rand(size=(3, 4))
random_tensor

tensor([[0.1050, 0.9233, 0.6787, 0.1013],
        [0.1322, 0.7855, 0.8836, 0.8854],
        [0.7250, 0.6160, 0.8540, 0.3937]])

In [ ]:
# zeros and ones
zeros = torch.zeros(size=(1, 2, 4))
print(zeros)
ones = torch.ones(size=(2, 5, 4))
print(ones)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [ ]:
# create a range of values
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Tensor info

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None) # defaults to None, which uses the default device

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
# change dtype
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)

float_16_tensor.dtype

torch.float16

In [ ]:
# check gpus stats
!nvidia-smi

Wed Nov  6 10:02:44 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
# change device (if it is available)
device = "cuda" if torch.cuda.is_available() else "cpu"
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               device=device)

float_16_tensor.device

device(type='cuda', index=0)

In [ ]:
# move tensors to different devices
tensor = torch.tensor([1, 2, 3])

# tensor not on GPU
print(tensor, tensor.device)

# move tensor to GPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [ ]:
# pytorch tensors & numpy
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
tensor2array = tensor.numpy()

print(array)
print(tensor)
print(tensor2array)

[1. 2. 3. 4. 5. 6. 7.]
tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)
[1. 2. 3. 4. 5. 6. 7.]


In [ ]:
# if tensor is on GPU cannot transform to numpy

try:
  tensor_on_gpu.numpy()
except TypeError as e:
  print(e)

# move to cpu, then convert to numpy
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
print(f"\nTensor converted into numpy {tensor_back_on_cpu}")

can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

Tensor converted into numpy [1 2 3]


## Tensor operations

In [ ]:
# basic operations
tensor = torch.tensor([1, 2, 3])
print(f"Sum {tensor + 10}")
print(f"Substraction {tensor - 10}")
print(f"Multiplication {tensor * 10}")
print(f"Multiplication (torch function) {torch.multiply(tensor, 10)}")
print(f"Element-wise multiplication {tensor * tensor}")
print(f"Matrix multiplication {tensor @ tensor}")
print(f"Original tensor is still unchanged  {tensor}")

Sum tensor([11, 12, 13])
Substraction tensor([-9, -8, -7])
Multiplication tensor([10, 20, 30])
Multiplication (torch function) tensor([10, 20, 30])
Element-wise multiplication tensor([1, 4, 9])
Matrix multiplication 14
Original tensor is still unchanged  tensor([1, 2, 3])


In [ ]:
# deal with shape errors
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

try:
  torch.matmul(tensor_A, tensor_B)
except RuntimeError as e:
  print(e)

mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)


In [ ]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [ ]:
# aggregation operations
x = torch.arange(0, 100, 10)
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


## Tensor dimension change

In [ ]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
x_reshaped = x.reshape(1, 7)
print(f"Reshaped tensor {x_reshaped}, {x_reshaped.shape}")
print(f"Remove extra dimension {x_reshaped.squeeze()}, {x_reshaped.squeeze().shape}")
print(f"Add an extra dimension {x_reshaped.unsqueeze(dim=0)}, {x_reshaped.unsqueeze(dim=0).shape}")
print(f"Stack our new tensor on top of itself five times {torch.stack([x_reshaped] * 5, dim=0)},  {torch.stack([x_reshaped] * 5, dim=0).shape}")


Reshaped tensor tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7])
Remove extra dimension tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7])
Add an extra dimension tensor([[[1., 2., 3., 4., 5., 6., 7.]]]), torch.Size([1, 1, 7])
Stack our new tensor on top of itself five times tensor([[[1., 2., 3., 4., 5., 6., 7.]],

        [[1., 2., 3., 4., 5., 6., 7.]],

        [[1., 2., 3., 4., 5., 6., 7.]],

        [[1., 2., 3., 4., 5., 6., 7.]],

        [[1., 2., 3., 4., 5., 6., 7.]]]),  torch.Size([5, 1, 7])


## Tensor indexing

In [ ]:
rank_1_tensor = torch.tensor([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(rank_1_tensor)
print("First:", rank_1_tensor[0])
print("Second:", rank_1_tensor[1])
print("Last:", rank_1_tensor[-1])
print("Everything:", rank_1_tensor[:])
print("Before 4:", rank_1_tensor[:4])
print("From 4 to the end:", rank_1_tensor[4:])
print("From 2, before 7:", rank_1_tensor[2:7])
print("Every other item:", rank_1_tensor[::2])
print("Reversed:", torch.flip(rank_1_tensor, [0]))

tensor([ 0,  1,  1,  2,  3,  5,  8, 13, 21, 34])
First: tensor(0)
Second: tensor(1)
Last: tensor(34)
Everything: tensor([ 0,  1,  1,  2,  3,  5,  8, 13, 21, 34])
Before 4: tensor([0, 1, 1, 2])
From 4 to the end: tensor([ 3,  5,  8, 13, 21, 34])
From 2, before 7: tensor([1, 2, 3, 5, 8])
Every other item: tensor([ 0,  1,  3,  8, 21])
Reversed: tensor([34, 21, 13,  8,  5,  3,  2,  1,  1,  0])


In [ ]:
# multi indexing
rank_2_tensor = torch.tensor([[1, 2],
                              [3, 4],
                              [5, 6]], dtype=torch.float16)

print("Second row:", rank_2_tensor[1, :])
print("Second column:", rank_2_tensor[:, 1])
print("Last row:", rank_2_tensor[-1, :])
print("First item in last column:", rank_2_tensor[0, -1])
print("Skip the first row:")
print(rank_2_tensor[1:, :], "\n")

Second row: tensor([3., 4.], dtype=torch.float16)
Second column: tensor([2., 4., 6.], dtype=torch.float16)
Last row: tensor([5., 6.], dtype=torch.float16)
First item in last column: tensor(2., dtype=torch.float16)
Skip the first row:
tensor([[3., 4.],
        [5., 6.]], dtype=torch.float16) 

