[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1X9pu2NkEl_Dao5KJVXGuzWEhaZ0-1kgC?usp=sharing)

In [ ]:
# Import required libraries
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

# Tensors

Tensors are n-dimensional arrays of numbers and serve as the foundational elements in machine learning. Their role is to represent data numerically..

<img src="https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-scalar-vector-matrix-tensor.png" alt="image" style="max-width:100px; max-height:100px;">

In [32]:
# scalar
scalar = tf.constant(17)
print(scalar)
print(len(scalar.shape))
print(scalar)

tf.Tensor(17, shape=(), dtype=int32)
0
tf.Tensor(17, shape=(), dtype=int32)


In [ ]:
# vector
vector = tf.constant([17, 14])
print(vector)
print(len(vector.shape))
print(vector.shape)

tf.Tensor([17 14], shape=(2,), dtype=int32)
1
(2,)


In [ ]:
# matrix
matrix = tf.constant([[17, 14],
                      [1, 2]])
print(matrix)
print(len(matrix.shape))
print(matrix.shape)

tf.Tensor(
[[17 14]
 [ 1  2]], shape=(2, 2), dtype=int32)
2
(2, 2)


In [ ]:
# tensors
tensor = tf.constant([[[1, 2, 3, 8],
                       [3, 6, 9, 7],
                       [2, 4, 5, 6]]])
print(tensor)
print(len(tensor.shape))
print(tensor.shape)

tf.Tensor(
[[[1 2 3 8]
  [3 6 9 7]
  [2 4 5 6]]], shape=(1, 3, 4), dtype=int32)
3
(1, 3, 4)


## Tensor creation

In [ ]:
# random tensors
random_tensor = tf.random.uniform(shape=(3, 4))
random_tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.7932713 , 0.30868077, 0.13068426, 0.57360625],
       [0.25740588, 0.9968169 , 0.7340361 , 0.9637555 ],
       [0.437724  , 0.07218885, 0.10139704, 0.19535422]], dtype=float32)>

In [ ]:
# zeros and ones
zeros = tf.zeros(shape=(1, 2, 4))
print(zeros)
ones = tf.ones(shape=(2, 5, 4))
print(ones)

tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(1, 2, 4), dtype=float32)
tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(2, 5, 4), dtype=float32)


In [ ]:
# create a range of values
zero_to_ten = tf.range(start=0, limit=10, delta=1)
zero_to_ten

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

## Tensor info

In [ ]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])
print("Original tensor:", rank_4_tensor)
print("Type of every element:", rank_4_tensor.dtype)
print("Number of axes:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor))

Original tensor: tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(3, 2, 4, 5), dtype=float32)
Type of every element: <dtype: 'float32'>
Number of axes: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


In [ ]:
# change dtype
float_16_tensor = tf.constant([3.0, 6.0, 9.0], dtype=tf.float16)

float_16_tensor.dtype

tf.float16

## Tensor operations

In [ ]:
# basic operations
tensor = tf.constant([1, 2, 3])
print(f"Sum {tensor + 10}")
print(f"Substraction {tensor - 10}")
print(f"Multiplication {tensor * 10}")
print(f"Multiplication (TensorFlow function) {tf.multiply(tensor, 10)}")
print(f"Element-wise multiplication {tensor * tensor}")
print(f"Original tensor is still unchanged  {tensor}")

Sum [11 12 13]
Substraction [-9 -8 -7]
Multiplication [10 20 30]
Multiplication (TensorFlow function) [10 20 30]
Element-wise multiplication [1 4 9]
Original tensor is still unchanged  [1 2 3]


In [ ]:
# deal with shape errors
tensor_A = tf.constant([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=tf.float32)

tensor_B = tf.constant([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=tf.float32)

try:
    tf.matmul(tensor_A, tensor_B)
except Exception as e:
    print(e)


{{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 


In [ ]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tf.transpose(tensor_B).shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tf.transpose(tensor_B).shape} <- inner dimensions match\n")
print("Output:\n")
output = tf.matmul(tensor_A, tf.transpose(tensor_B))
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = (3, 2), tensor_B = (3, 2)

New shapes: tensor_A = (3, 2) (same as above), tensor_B.T = (2, 3)

Multiplying: (3, 2) * (2, 3) <- inner dimensions match

Output:

tf.Tensor(
[[ 27.  30.  33.]
 [ 61.  68.  75.]
 [ 95. 106. 117.]], shape=(3, 3), dtype=float32)

Output shape: (3, 3)


In [ ]:
# aggregation operations
x = tf.range(0, 100, 10)
print(f"Minimum: {tf.reduce_min(x)}")
print(f"Maximum: {tf.reduce_max(x)}")
print(f"Mean: {tf.reduce_mean(x)}")
print(f"Sum: {tf.reduce_sum(x)}")

Minimum: 0
Maximum: 90
Mean: 45
Sum: 450


## Tensor dimension change

In [ ]:
x = tf.range(1.0, 8.0)
x, x.shape

(<tf.Tensor: shape=(7,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7.], dtype=float32)>,
 TensorShape([7]))

In [ ]:
x_reshaped = tf.reshape(x, (1, 7))
print(f"Reshaped tensor {x_reshaped}, {x_reshaped.shape}")
print(f"Remove extra dimension {tf.squeeze(x_reshaped)}, {tf.squeeze(x_reshaped).shape}")
print(f"Add an extra dimension {tf.expand_dims(x_reshaped, axis=0)}, {tf.expand_dims(x_reshaped, axis=0).shape}")
print(f"Stack our new tensor on top of itself five times {tf.stack([x_reshaped] * 5, axis=0)}, {tf.stack([x_reshaped] * 5, axis=0).shape}")

Reshaped tensor [[1. 2. 3. 4. 5. 6. 7.]], (1, 7)
Remove extra dimension [1. 2. 3. 4. 5. 6. 7.], (7,)
Add an extra dimension [[[1. 2. 3. 4. 5. 6. 7.]]], (1, 1, 7)
Stack our new tensor on top of itself five times [[[1. 2. 3. 4. 5. 6. 7.]]

 [[1. 2. 3. 4. 5. 6. 7.]]

 [[1. 2. 3. 4. 5. 6. 7.]]

 [[1. 2. 3. 4. 5. 6. 7.]]

 [[1. 2. 3. 4. 5. 6. 7.]]], (5, 1, 7)


## Tensor indexing

In [34]:
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(rank_1_tensor)
print("First:", rank_1_tensor[0])
print("Second:", rank_1_tensor[1])
print("Last:", rank_1_tensor[-1])
print("Everything:", rank_1_tensor[:])
print("Before 4:", rank_1_tensor[:4])
print("From 4 to the end:", rank_1_tensor[4:])
print("From 2, before 7:", rank_1_tensor[2:7])
print("Every other item:", rank_1_tensor[::2])
print("Reversed:", rank_1_tensor[::-1])

tf.Tensor([ 0  1  1  2  3  5  8 13 21 34], shape=(10,), dtype=int32)
First: tf.Tensor(0, shape=(), dtype=int32)
Second: tf.Tensor(1, shape=(), dtype=int32)
Last: tf.Tensor(34, shape=(), dtype=int32)
Everything: tf.Tensor([ 0  1  1  2  3  5  8 13 21 34], shape=(10,), dtype=int32)
Before 4: tf.Tensor([0 1 1 2], shape=(4,), dtype=int32)
From 4 to the end: tf.Tensor([ 3  5  8 13 21 34], shape=(6,), dtype=int32)
From 2, before 7: tf.Tensor([1 2 3 5 8], shape=(5,), dtype=int32)
Every other item: tf.Tensor([ 0  1  3  8 21], shape=(5,), dtype=int32)
Reversed: tf.Tensor([34 21 13  8  5  3  2  1  1  0], shape=(10,), dtype=int32)


In [35]:
# multi indexing
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)

print("Second row:", rank_2_tensor[1, :])
print("Second column:", rank_2_tensor[:, 1])
print("Last row:", rank_2_tensor[-1, :])
print("First item in last column:", rank_2_tensor[0, -1])
print("Skip the first row:")
print(rank_2_tensor[1:, :], "\n")

Second row: tf.Tensor([3. 4.], shape=(2,), dtype=float16)
Second column: tf.Tensor([2. 4. 6.], shape=(3,), dtype=float16)
Last row: tf.Tensor([5. 6.], shape=(2,), dtype=float16)
First item in last column: tf.Tensor(2.0, shape=(), dtype=float16)
Skip the first row:
tf.Tensor(
[[3. 4.]
 [5. 6.]], shape=(2, 2), dtype=float16) 



In [33]:
# tensors & numpy
import numpy as np
array = np.arange(1.0, 8.0)
tensor = tf.convert_to_tensor(array)
tensor2array = tensor.numpy()

print(array)
print(tensor)
print(tensor2array)

[1. 2. 3. 4. 5. 6. 7.]
tf.Tensor([1. 2. 3. 4. 5. 6. 7.], shape=(7,), dtype=float64)
[1. 2. 3. 4. 5. 6. 7.]
